# Form implementation generated from reading ui file 'c:\Users\letan\OneDrive\Máy tính\Macloed\uic\plot.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 500)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 26, 700, 460))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_T1 = QtWidgets.QWidget()
        self.tab_T1.setObjectName("tab_T1")
        self.T1 = QtWidgets.QWidget(self.tab_T1)
        self.T1.setGeometry(QtCore.QRect(0, 0, 690, 460))
        self.T1.setObjectName("T1")
        self.tabWidget.addTab(self.tab_T1, "")
        self.tab_T2 = QtWidgets.QWidget()
        self.tab_T2.setObjectName("tab_T2")
        self.T2 = QtWidgets.QWidget(self.tab_T2)
        self.T2.setGeometry(QtCore.QRect(0, 0, 690, 460))
        self.T2.setObjectName("T2")
        self.tabWidget.addTab(self.tab_T2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_T1), _translate("Form", "變色前光譜圖"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_T2), _translate("Form", "變色后光譜圖"))
