# Form implementation generated from reading ui file 'c:\Users\letan\OneDrive\Máy tính\Macleod2\uic\targets.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 480)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(8, 27, 345, 445))
        self.tabWidget.setMaximumSize(QtCore.QSize(345, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Before = QtWidgets.QWidget()
        self.tab_Before.setObjectName("tab_Before")
        self.tableBeforeWidget = QtWidgets.QTableWidget(self.tab_Before)
        self.tableBeforeWidget.setGeometry(QtCore.QRect(0, 0, 345, 445))
        self.tableBeforeWidget.setObjectName("tableBeforeWidget")
        self.tableBeforeWidget.setColumnCount(2)
        self.tableBeforeWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tableBeforeWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tableBeforeWidget.setHorizontalHeaderItem(1, item)
        self.tableBeforeWidget.horizontalHeader().setDefaultSectionSize(145)
        self.tabWidget.addTab(self.tab_Before, "")
        self.tab_After = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_After.setFont(font)
        self.tab_After.setObjectName("tab_After")
        self.tableAfterWidget = QtWidgets.QTableWidget(self.tab_After)
        self.tableAfterWidget.setGeometry(QtCore.QRect(0, 0, 345, 445))
        self.tableAfterWidget.setObjectName("tableAfterWidget")
        self.tableAfterWidget.setColumnCount(2)
        self.tableAfterWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tableAfterWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tableAfterWidget.setHorizontalHeaderItem(1, item)
        self.tableAfterWidget.horizontalHeader().setDefaultSectionSize(145)
        self.tabWidget.addTab(self.tab_After, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableBeforeWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Wavelength"))
        item = self.tableBeforeWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Reflectance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Before), _translate("Form", "Before"))
        item = self.tableAfterWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Wavelength"))
        item = self.tableAfterWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Reflectance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_After), _translate("Form", "After"))
